name: Convert Python to HTML and Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write    # Required for GitHub Pages deployment

on:
  push:
    branches:
      - main
    paths:
      - 'notebooks/*.py'
  pull_request:
    branches:
      - main
    paths:
      - 'notebooks/*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert jupytext

      - name: Convert PY to HTML
        run: |
          mkdir -p public  # Create a directory to store the HTML files
          cd notebooks
          for file in *.py; do
            if [ -f "$file" ]; then
              jupytext --to notebook "$file"
              jupyter nbconvert --to html "${file%.py}.ipynb" --output-dir=../public
            fi
          done

      - name: Create index.html (if needed)
        run: |
          cd public
          if [ ! -f "index.html" ]; then
            echo "<h1>Generated Content</h1><p>This page was generated from Python notebooks.</p>" > index.html
          fi
          echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">" >> index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public  # Upload the 'public' directory

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
