name: Convert Python to HTML and Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
    paths:
      - 'notebooks/**'
  pull_request:
    branches:
      - main
    paths:
      - 'notebooks/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert jupytext

      - name: Convert PY/ipynb to HTML
        run: |
          mkdir -p public
          cd notebooks
          for file in *; do
            if [ -f "$file" ]; then
              if [[ "$file" == *.py ]]; then
                jupytext --to notebook "$file"
                jupyter nbconvert --to html "${file%.py}.ipynb" --output-dir=../public
              elif [[ "$file" == *.ipynb ]]; then
                jupyter nbconvert --to html "$file" --output-dir=../public
              fi
            fi
          done
          cd ../public
          #  Create a index.html that links to the generated content
          echo "<h1>Generated Content</h1>" > index.html
          echo "<p>This page displays content generated from Python notebooks:</p>" >> index.html
          echo "<ul>" >> index.html
          for generated_file in *.html; do
            if [[ "$generated_file" != "index.html" ]]; then
              echo "  <li><a href=\"$generated_file\">$generated_file</a></li>" >> index.html
            fi
          done
          echo "</ul>" >> index.html
          echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">" >> index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4