name: Convert Python to HTML

permissions:
  contents: write
  pages: write
  id-token: write    # Required for Pages deployment

on:
  push:
    branches:
      - main
    paths:
      - 'notebooks/*.py'
  pull_request:
    branches:
      - main
    paths:
      - 'notebooks/*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert jupytext
          
      - name: Convert PY to HTML
        run: |
          cd notebooks
          for file in *.py; do
            if [ -f "$file" ]; then
              jupytext --to notebook "$file"
              jupyter nbconvert --to html "${file%.py}.ipynb"
            fi
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./notebooks

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4