name: Deploy Notebooks

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Create Site
        run: |
          pip install jupyter nbconvert jupytext
          mkdir -p _site
          cd notebooks
          # Create index
          echo "# Notebook Index" > index.md
          echo "## Available notebooks:" >> index.md
          for f in *.py; do
            if [ -f "$f" ]; then
              name=$(basename "$f" .py)
              echo "* [$name]($name.html)" >> index.md
            fi
          done
          jupyter nbconvert --to html index.md --output-dir=../_site
          # Convert notebooks
          for f in *.py; do
            if [ -f "$f" ]; then
              jupytext --to notebook "$f"
              jupyter nbconvert --to html "${f%.py}.ipynb" --output-dir=../_site
            fi
          done

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4